# Generated by Django 4.2.7 on 2023-11-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
